version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: sh -c "cd app && npm start"
    ports:
      - "3000:3000"
    stdin_open: true
